PI = 3.14
r = float(input("Enter the radius of the circle"))
print(r)
l = int(input("Enter the length of the rectangle"))
print(l)
b = int(input("Enter the breadth of the rectangle"))
print(b)
x =int(input("Enter the side of the square"))
print(x)
print("Area of the circle = ",(PI*r*r))
print("Perimeter of the circle = ", 2*3.14*r)
print("Area of the square = ",x*x)
print("Perimeter of the square = ", 4*x)
print("Area of the rectangle = ",l*b)
print("Perimeter of the rectangle = ", 2*(l+b))
